/*
 * SEVEN_SEGMENT_KIT_Program.c
 *
 * Created: 25/11/2023 02:27:26 م
 *  Author: Moustafa El-hanash
 */ 


#include "SEVEN_SEGMENT_KIT_Private.h"


void SEVEN_SEGMENT_KIT_INIT(void)
{
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_CENTRAL_PORT,EN1_PIN,GPIO_OUTPUT);
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_CENTRAL_PORT,EN2_PIN,GPIO_OUTPUT);
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_CENTRAL_PORT,DIP_PIN,GPIO_OUTPUT);
	
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_DATA_PORT,DATA_A_PIN,GPIO_OUTPUT);
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_DATA_PORT,DATA_B_PIN,GPIO_OUTPUT);
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_DATA_PORT,DATA_C_PIN,GPIO_OUTPUT);
	GPIO_SETPIN_DIRECTION(SEVEN_SEGMENT_DATA_PORT,DATA_D_PIN,GPIO_OUTPUT);
}

void SEVEN_SEGMENT_KIT_EN1_ONLY(void)
{
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN1_PIN,GPIO_HIGH);
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN2_PIN,GPIO_LOW);	
}
void SEVEN_SEGMENT_KIT_EN2_ONLY(void)
{
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN1_PIN,GPIO_LOW);
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN2_PIN,GPIO_HIGH);
}
void SEVEN_SEGMENT_KIT_ENABLE_ALL(void)
{
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN1_PIN,GPIO_HIGH);
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN2_PIN,GPIO_HIGH);
}
void SEVEN_SEGMENT_KIT_DISABLE_ALL(void)
{
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN1_PIN,GPIO_LOW);
	GPIO_SETPIN_VALUE(SEVEN_SEGMENT_CENTRAL_PORT,EN2_PIN,GPIO_LOW);
}

void SEVEN_SEGMENT_KIT_DISPLAY(uint8 num)
{
	
	ASSIGN_BIT(PORTA,4,GET_BIT(num,0));
	ASSIGN_BIT(PORTA,5,GET_BIT(num,1));
	ASSIGN_BIT(PORTA,6,GET_BIT(num,2));
	ASSIGN_BIT(PORTA,7,GET_BIT(num,3));
}